import { describe, it, expect, vi } from "vitest";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { readZoneFiles } from "@src/tools/generate-world-sql/zone-loader.js";
import { generateSql } from "@src/tools/generate-world-sql/sql-generator.js";
import type { Logger } from "@src/tools/lib/logger.js";

const FIXTURES_DIR = path.resolve(__dirname, "fixtures");

function makeLog(): Logger {
  return {
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
    debug: vi.fn(),
    success: vi.fn(),
    forZone() {
      return makeLog();
    }
  } as unknown as Logger;
}

describe("generateSql (end-to-end)", () => {
  it("produces SQL matching the expected snapshot", async () => {
    const log = makeLog();
    const zones = await readZoneFiles(["zone-268.json"], FIXTURES_DIR, log);
    const { sql } = generateSql(zones, log);

    // Strip the header (first 4 lines are timestamp-dependent + blank) and
    // the DELETE block (next 7 lines) to compare only the data statements.
    const dataLines = sql
      .split("\n")
      .filter((line) => !line.startsWith("--") && !line.startsWith("DELETE") && line !== "");

    const expected = await readFile(
      path.join(FIXTURES_DIR, "zone-268.expected.sql"),
      "utf-8"
    );
    const expectedLines = expected
      .split("\n")
      .filter((line) => !line.startsWith("--") && line !== "");

    expect(dataLines).toEqual(expectedLines);
  });

  it("returns correct stats", async () => {
    const zones = await readZoneFiles(["zone-268.json"], FIXTURES_DIR, makeLog());
    const { stats } = generateSql(zones, makeLog());

    expect(stats.zones).toBe(1);
    expect(stats.rooms).toBe(3);
    expect(stats.exits).toBe(3);
    expect(stats.extraDescs).toBe(2);
    expect(stats.zoneCommands).toBe(2);
    expect(stats.triggers).toBe(1);
  });

  it("reports zero warnings for clean data", async () => {
    const zones = await readZoneFiles(["zone-268.json"], FIXTURES_DIR, makeLog());
    const { warnings } = generateSql(zones, makeLog());

    expect(warnings).toBe(0);
  });

  it("includes the header and DELETE preamble", async () => {
    const zones = await readZoneFiles(["zone-268.json"], FIXTURES_DIR, makeLog());
    const { sql } = generateSql(zones, makeLog());

    expect(sql).toContain("-- 0002_seed_data.sql");
    expect(sql).toContain("-- Auto-generated by generate-world-sql");
    expect(sql).toContain("-- Source: 1 zone files");
    expect(sql).toContain("DELETE FROM room_triggers;");
    expect(sql).toContain("DELETE FROM zones;");
  });

  it("emits DELETE statements in FK-safe order", async () => {
    const zones = await readZoneFiles(["zone-268.json"], FIXTURES_DIR, makeLog());
    const { sql } = generateSql(zones, makeLog());
    const lines = sql.split("\n");
    const deleteLines = lines.filter((l) => l.startsWith("DELETE"));

    expect(deleteLines).toEqual([
      "DELETE FROM room_triggers;",
      "DELETE FROM room_extra_descriptions;",
      "DELETE FROM exits;",
      "DELETE FROM zone_commands;",
      "DELETE FROM rooms;",
      "DELETE FROM zones;"
    ]);
  });
});
