/**
 * Orchestrates the individual SQL generators to produce a complete
 * idempotent seed migration from parsed zone data.
 *
 * Each table has its own generator under `./generators/` that can be
 * tested independently.
 *
 * @module
 */

import type { Logger } from "../lib/logger.js";
import type { ZoneFile } from "../lib/types.js";
import { generateZoneSql } from "./generators/zone-generator.js";
import { generateRoomSql } from "./generators/room-generator.js";
import { generateExitSql } from "./generators/exit-generator.js";
import { generateExtraDescriptionSql } from "./generators/extra-description-generator.js";
import { generateTriggerSql } from "./generators/trigger-generator.js";

export interface GenerateStats {
  zones: number;
  rooms: number;
  exits: number;
  extraDescs: number;
  zoneCommands: number;
  triggers: number;
}

export interface GenerateResult {
  sql: string;
  stats: GenerateStats;
  warnings: number;
}

export function generateSql(zones: ZoneFile[], log: Logger): GenerateResult {
  const lines: string[] = [];
  const stats: GenerateStats = {
    zones: 0,
    rooms: 0,
    exits: 0,
    extraDescs: 0,
    zoneCommands: 0,
    triggers: 0
  };
  let warnings = 0;

  // Header
  lines.push("-- 0002_seed_data.sql");
  lines.push("-- Auto-generated by generate-world-sql");
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Source: ${zones.length} zone files`);
  lines.push("");

  // Delete in FK-safe order (children first)
  lines.push("DELETE FROM room_triggers;");
  lines.push("DELETE FROM room_extra_descriptions;");
  lines.push("DELETE FROM exits;");
  lines.push("DELETE FROM zone_commands;");
  lines.push("DELETE FROM rooms;");
  lines.push("DELETE FROM zones;");
  lines.push("");

  for (const zoneFile of zones) {
    const z = zoneFile.zone;
    const zoneId = Number(zoneFile.id);
    const zoneLog = log.forZone(String(zoneId));

    // Zone + zone commands
    lines.push(`-- Zone ${zoneId}: ${z.name}`);
    const zoneResult = generateZoneSql(zoneId, z);
    lines.push(...zoneResult.lines);
    stats.zones += zoneResult.count;
    stats.zoneCommands += z.commands.length;

    // Rooms and their children
    for (const room of zoneFile.world) {
      const roomResult = generateRoomSql(room, zoneId);
      lines.push(...roomResult.lines);
      stats.rooms += roomResult.count;

      for (const exit of room.exits) {
        const exitResult = generateExitSql(room.vnum, exit);
        lines.push(...exitResult.lines);
        stats.exits += exitResult.count;
      }

      const edResult = generateExtraDescriptionSql(room.vnum, room.extra_descriptions, zoneLog);
      lines.push(...edResult.lines);
      stats.extraDescs += edResult.count;
      warnings += edResult.warnings;

      const trigResult = generateTriggerSql(room.vnum, room.triggers, zoneLog);
      lines.push(...trigResult.lines);
      stats.triggers += trigResult.count;
      warnings += trigResult.warnings;
    }

    lines.push("");
    zoneLog.debug(`${zoneFile.world.length} rooms, ${z.commands.length} commands`);
  }

  return { sql: lines.join("\n"), stats, warnings };
}
